name: Woven OpenDAPI CI
# Invoke for every Pull Request and push to main branch
on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # Checkout the correct branch instead of detached HEAD
        ref: ${{ github.event.pull_request.head.ref || github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Woven DAPI CI
      shell: bash
      run: |
        pip install opendapi
        dapi_ci_github
      env:
        # Store credentials in Github Repo secrets
        DAPI_SERVER_HOST: https://api.wovencollab.com
        DAPI_SERVER_API_KEY: ${{ secrets.DAPI_SERVER_API_KEY }}

        # Configure when DAPIs should be registered.
        # PRs do not register but only validate
        MAINLINE_BRANCH_NAME: "main"
        REGISTER_ON_MERGE_TO_MAINLINE: True
        GITHUB_TOKEN: ${{ github.token }}
